/*
 * This source file was generated by the Gradle 'init' task
 */
package sky.backend;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

class AppTest {
    @Test void testMapper() {
        try {
            ObjectMapper mapper = new ObjectMapper();
            Map<String, Object> body = mapper.readValue("{\"name\":\"test\"}", new TypeReference<Map<String, Object>>() {});
            String name = body.getOrDefault("name", "World").toString();
            System.out.println(name);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            assertNotNull(null, "null");
        }
        
    }
}
